# This file configures the Dart static analyzer.
# For a full list of rules and their documentation, see https://dart.dev/lints.
 
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # === Style Rules ===
    # Enforce single quotes for strings.
    prefer_single_quotes: true
    # Use `package:` imports instead of relative imports for files in `lib/`.
    always_use_package_imports: true

    # === Best Practice / Error Prevention ===
    # Prefer final for local variables that are not reassigned.
    prefer_final_locals: true
    # Avoid passing booleans as positional parameters to improve readability.
    avoid_positional_boolean_parameters: true
