name: airsoft_telemetry_flutter
description: "Flutter app for Airsoft Telemetry, providing real-time data tracking and analysis for airsoft players."

# Prevents accidental publishing to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.5+5

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons.
  cupertino_icons: ^1.0.6

  # For local database storage (SQLite).
  sqflite: ^2.3.3
  # For finding the correct local path to store the database.
  path_provider: ^2.1.3

  # For accessing device location (GPS).
  geolocator: ^12.0.0

  # For handling runtime permissions (location, notifications, etc.).
  permission_handler: ^11.3.1

  # For simple key-value storage (user preferences).
  shared_preferences: ^2.2.3
  # For creating and handling CSV data for export.
  csv: ^6.0.0

  # For path operations in database service
  path: ^1.8.3

  plugin_platform_interface: ^2.1.8

dev_dependencies:
  # Documentation:
  # The 'flutter_test' dependency utilizes the Flutter SDK to provide a framework for writing and running 
  # unit tests and widget tests. It is essential for validating the correctness of individual Flutter components.
  flutter_test:
    sdk: flutter

  # The 'integration_test' dependency leverages the Flutter SDK to enable end-to-end integration testing, 
  # allowing you to simulate user interactions and verify the behavior of the complete application. This 
  # facilitates comprehensive testing of how different parts of your app work together.
  integration_test:
    sdk: flutter
  # For mocking in tests
  mocktail: ^1.0.3

  # For SQLite testing
  sqflite_common_ffi: ^2.3.3

  # Recommended lints for Flutter projects.
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
