name: airsoft_telemetry_flutter
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons.
  cupertino_icons: ^1.0.6

  # For local database storage (SQLite).
  sqflite: ^2.3.3
  # For finding the correct local path to store the database.
  path_provider: ^2.1.3

  # For accessing device location (GPS).
  location: ^6.0.2

  # For handling runtime permissions (location, notifications, etc.).
  permission_handler: ^11.3.1

  # For simple key-value storage (user preferences).
  shared_preferences: ^2.2.3

  # For creating and handling CSV data for export.
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter projects.
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
