# .github/workflows/auto-tag.yml
name: Auto Tag on Main Push

on:
  push:
    branches:
      - main

permissions:
  contents: write # Required to push new tags

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for version calculation

      - name: Calculate next version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          # This action reads commits and outputs the next version
          # It will only create a new version if a fix:, feat:, or BREAKING CHANGE: is found
          bump_each_commit: false

      - name: Create and push new tag
        if: steps.version.outputs.changed
        uses: anothrNick/github-tag-action@1.67.0
        with:
          new_tag: ${{ steps.version.outputs.version_tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}