# .github/workflows/release.yml
name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # Required to push new tags and commit changes

jobs:
  release:
    # This condition prevents the workflow from running on commits made by this action
    if: "!contains(github.event.head_commit.message, 'chore(release):')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for version calculation

      - name: Calculate next version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: false

      # The following steps only run if a version change was detected
      - name: Update version in pubspec.yaml
        if: steps.version.outputs.changed
        run: |
          # Use the version (e.g., 1.2.1) not the tag (v1.2.1)
          VERSION_NAME="${{ steps.version.outputs.version }}"
          BUILD_NUMBER=${{ github.run_number }}
          perl -pi -e "s/version: .*/version: $VERSION_NAME+$BUILD_NUMBER/" pubspec.yaml
          echo "Updated pubspec.yaml to version: $VERSION_NAME+$BUILD_NUMBER"
          cat pubspec.yaml

      - name: Commit and Tag version bump
        if: steps.version.outputs.changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(release): set version to ${{ steps.version.outputs.version }}"
          tagging_message: "${{ steps.version.outputs.version_tag }}"
          file_pattern: pubspec.yaml